miurla/morphic

.env.local.example
README.md

Remove the values passed from Vercel's env parameters, as they cannot be made optional.
Also, comment out env.local and explicitly indicate that it is optional.

Update .env.local.example and README.md

---

app/action.tsx
lib/agents/researcher.tsx

closes: #14 #15 
- Handling of search errors
- Fixed to fill with spaces because an error occurs if the query parameter of the Tavily API is less than 5 characters

Refactor researcher function and handle search errors

---

.env.local.example
README.md
lib/agents/inquire.tsx
lib/agents/query-suggestor.tsx
lib/agents/researcher.tsx
lib/agents/task-manager.tsx

If not set, the default is to use gpt-4-turbo.

Allow users to customize the model

---

README.md

Adding button to give community access to a 2nd option for self hosting via a one-click deployment template on RepoCloud's affordable cloud service.

Adding additional deploy option to README.md

---

components/chat-panel.tsx

the bottom div with the New button currently blocks pointer events, which isn't useful because the div is transparent.

allow pointer events to pass through container

---

app/action.tsx
components/search-section.tsx
lib/agents/researcher.tsx
lib/types/index.ts

Fixed the UI to be updated correctly when multiple search tools are called.

Fix Researcher

---

README.md

Cloudflare Pages is a free hosting option that provides unlimited bandwidth and faster performance compared to Vercel. It can be a good alternative to consider for deploying web projects..

Add Cloudflare Pages deployment option to README.md

---

components/history.tsx

when i delete redis `chat:xxx`, just whole page down

fix history: chat maybe undefined

---

docker-compose.yaml

This pull request introduces a new Docker Compose configuration to streamline the setup and execution of the Morphic project for local development environments. The `docker-compose.yml` file follows the defaults set out in the current README.
Docker Compose File: A `docker-compose.yml` file has been added to the root of the project. This file defines the morphic service, specifying how it should be built and run:
* The Docker context is set to the current directory, with the `Dockerfile` specified for building the image.
* Reads .env.local for environment variables aligning with the README
The service is configured to run the command bun dev, aligning with the README.
Port forwarding is configurable but by default maps the container's port 3000 to localhost:3000.
1. Ensure Docker and …

feat: Add docker-compose file

---

.env.local.example
components/user-message.tsx

Since this repo does not have authentication, the search results page itself is shareable. Therefore, the share feature is made optional and disabled by default. If enabling the feature, authentication needs to be implemented.

Make the share feature optional

---

lib/agents/researcher.tsx

This pull request introduces a new feature to the `researcher` function in the `researcher.tsx` file. The feature adds the current date and time to the system prompt that is passed to the Language Model (LLM). The date and time are fetched programmatically and change based on the system time.
Ensures that any web searches related to time sensitive topics have the correct current datetime e.g. 
`researcher` Function: The `researcher` function in the `researcher.tsx` file has been updated to include the current date and time in the system prompt:
* A new constant `currentDate` is declared and assigned the current date and time using the JavaScript `Date` object.
The `currentDate` is then converted to a string and included in the system prompt that is passed to the …

feat: Add current date and time to prompt for researcher

---

.env.local.example
README.md
app/actions.tsx
components/retrieve-section.tsx
components/search-results.tsx
lib/agents/researcher.tsx
lib/agents/tools/index.tsx
lib/agents/tools/retrieve.tsx
lib/agents/tools/search.tsx
lib/schema/retrieve.tsx

This PR introduces a tool that retrieves content from specific URLs provided by the user. The tool leverages the Exa API to fetch the content and display it in the UI.
- Added a new tool in `lib/agents/tools/retrieve.tsx` that retrieves content from the web.
- The tool requires an Exa API Key to function.
- If the retrieval is successful, the content is displayed using the `RetrieveSection` component.
- In case of an error, an appropriate message is displayed to the user.
- Exa API Key must be set in the environment variables.
- Issue #92

Add Tool to Retrieve Page Content from Specific URLs

---

.env.local.example
lib/agents/tools/index.tsx
lib/agents/tools/retrieve.tsx
lib/schema/retrieve.tsx

#155 
`jina.ai/reader` will be used instead of exa.ai because it offers a larger free tier and the response isn't bad either.
https://github.com/miurla/morphic/pull/155#issuecomment-2118858686

Refactor retrieveTool to use jina.ai

---

components/search-section.tsx
lib/agents/researcher.tsx

closes: #159
Due to the addition of the retry tool, the URL of the search results was being further read by the retry tool.
Fixed the prompt.
Also, the section titles were not unified, so they were corrected.

Add restriction to retrieve tool

---

components/chat-panel.tsx

- Update handleClear function
- Disabled the `new` button while generating.
This will likely resolve issue #169 as well.

chore: Update the handleClear function to disable the button during generation

---

app/actions.tsx
app/page.tsx
app/search/page.tsx
components/chat-panel.tsx

Hi,
nanoid is deprecated by AI SDK, use `generateId` instead : https://github.com/vercel/ai/pull/1929/commits/b4db8b20dda9c7ca0853e8a564602aeac707a733

chore: nanoid is deprecated, use `generateId` instead

---

components/answer-section-generated.tsx
lib/agents/researcher.tsx
lib/agents/writer.tsx

There is a bug where a new instance of the answer section is displayed once when the next section is added.
Update the generated answer section if the response is generated. This ensures that the answer section prevents an empty answer from being displayed even if a new instance is called.

fix: Add generated answer section component

---

components/search-results-image.tsx
lib/agents/tools/search.tsx
lib/types/index.ts

The `include_image_descriptions` parameter has been added to Tavily's Search API as a Beta feature. Enabling this parameter allows the LLM to understand the descriptions of images, which will be reflected in the answers.
You can also check the responses in Tavily's Playground:  https://app.tavily.com/playground
(This parameter reflects feedback from Morphic to the Tavily team)

feat: Support the include_image_descriptions parameter of Tavily

---

components/footer.tsx

This pull request updates footer component to reflect recent changes in Twitter's branding:
1. Modified the icon import from 'react-icons/si':
- Replaced SiTwitter with SiX to use the new X icon
2. Updated the Twitter/X link:
- Changed the URL from https://twitter.com/morphic_ai to https://x.com/morphic_ai
These changes ensure footer stays current with Twitter's rebranding to X. The functionality remains the same, but users will now see the X icon and be directed to the x.com domain when clicking the link.
Please review and test to ensure the footer renders correctly with the new icon and that the link works as expected.

Update Twitter icon import and URL

---

.github/ISSUE_TEMPLATE/bug_report.yml
README.md

Currently, due to build errors occurring in Cloudflare Pages, it will be removed from the deployment options: https://github.com/miurla/morphic/issues/114

chore: Update readme and bug report template

---

.env.local.example
README.md
lib/utils/index.ts

Until now, Groq was only applied to the Writer agent, but it has been made selectable as a provider option.
Only models compatible with tool use are available.
Set the following environment variables:
```
```
Along with this change, the writer agent and `SPECIFIC_API_xxx` have been removed.

feat: Support Groq AI Provider

---

lib/agents/tools/search.tsx
lib/schema/search.tsx

closes: #357 
Solved the issue of the Gemini model not calling tools
Cause:
> The Google Generative AI API uses a subset of the OpenAPI 3.0 schema, which does not support features such as unions.
We are using enum in the schema specification, but it was not supported by the Google Generative AI API
doc: https://sdk.vercel.ai/providers/ai-sdk-providers/google-generative-ai#troubleshooting-schema-limitations
issue: https://github.com/vercel/ai/issues/2926#issuecomment-2337289714

fix: Update search depth parameter to accept string values

---

components/chat-panel.tsx

This PR addresses [issue #360](https://github.com/miurla/morphic/issues/360), which involves premature form submission when pressing the Enter key during IME input on macOS Safari and other environments that use text composition.
1. **Composition State Management**:
- Added `isComposing` state to track when the user is in the middle of IME (Input Method Editor) input.
- The form submission is now blocked while composition is ongoing, preventing premature submissions.
2. **Enter Key Behavior with Delay**:
- The Enter key is disabled briefly after composition ends using `setEnterDisabled`, ensuring that form submission occurs only when composition has fully completed.
- Added a **300 millisecond delay** after composition ends before re-enabling the Enter key, using `setTimeout`. This …

Fix: Handle Text Composition and Prevent Premature Form Submission on Enter Key (#360)

---

.env.local.example
components/search-section.tsx
lib/streaming/parse-tool-call.ts
lib/streaming/tool-execution.ts
lib/tools/search.ts
lib/types/models.ts
lib/utils/registry.ts

ref: #419 #420
Make Ollama models configurable through .env
Use `NEXT_PUBLIC_OLLAMA_MODEL`. Falls back to 'deepseek-r1' if not set.
For inference models like deepseek-r1, made it possible to optionally set a separate model for tool calls using `NEXT_PUBLIC_OLLAMA_TOOL_CALL_MODEL`. If not set, it uses `NEXT_PUBLIC_OLLAMA_MODEL`

feat: update Ollama model configuration and enhance tool call support

---

lib/utils/registry.ts

When using model names with multiple colons (e.g., "ollama:deepseek-r1:32b"), the function was only capturing the first part after the provider ("deepseek-r1"), dropping the rest of the model specification: https://github.com/miurla/morphic/issues/420#issuecomment-2636302096
Modified the model name parsing to preserve everything after the provider prefix, allowing for proper handling of complex model names like "ollama:deepseek-r1:32b".
Before:
- Input: "ollama:deepseek-r1:32b"
- Result: modelName = "deepseek-r1"
After:
- Input: "ollama:deepseek-r1:32b"
- Result: modelName = "deepseek-r1:32b"

fix: preserve full model name after provider

---

.github/workflows/docker-build.yml
Dockerfile
docker-compose.yaml

- Add multi-stage Dockerfile for optimized builds
- Configure GitHub Actions for automated image builds
- Update docker-compose.yaml for prebuild support

feat: add docker prebuild and GitHub Actions workflow

---

Dockerfile
docker-compose.yaml

fix: #432 
- Update docker-compose.yaml to use bun start
- Ensure consistency with Dockerfile CMD
- Optimize for production environment

fix: use bun start for production mode in Docker

---

README.md

Due to limitations with NEXT_PUBLIC_ environment variables in pre-built Docker images, removing the prebuilt image documentation from README. Users should use docker-compose up instead for now.
Related to #439

docs: remove prebuilt image documentation

---

lib/streaming/handle-stream-finish.ts

- Add environment variable `NEXT_PUBLIC_ENABLE_SAVE_CHAT_HISTORY` to control chat history saving
- When set to 'false', the function returns early without saving chat history

fix: add env flag to disable chat history saving

---

components/model-selector.tsx

- Add filter to groupModelsByProvider to only show enabled models
- Improve user experience by hiding unavailable models

fix: filter out disabled models from UI

---

lib/config/default-models.json
lib/config/models.ts
middleware.ts

This PR addresses the issue reported in #469 where models fail to load despite the presence of `models.json`.
The application was encountering issues when trying to fetch `models.json` in certain environments:
1. When using `0.0.0.0` address in local development, which can cause connection issues with HTTPS
2. In Vercel preview environments where authentication is required, causing HTML login pages to be returned instead of JSON
3. When running behind proxies where URL construction might be incorrect
- Created a default models configuration in `lib/config/default-models.json`
- Modified `getModels()` function to implement a multi-level fallback strategy:
1. First attempt: Fetch from URL (using headers for proper URL construction)
2. If fetch fails or returns HTML: Fall back to default …

Fix models.json loading in various environments

---

.env.local.example
lib/config/models.ts

Added support for the `BASE_URL` environment variable to solve resource loading issues (especially `models.json`) in Docker environments. This makes Docker setup easier and provides a more intuitive configuration for users.
1. **lib/config/models.ts**:
- Check for the `BASE_URL` environment variable first and prioritize it if set
- Fall back to header-based URL retrieval if the environment variable is invalid
- Refactored code to separate header-based URL retrieval into a helper function
2. **.env.local.example**:
- Added documentation for the `BASE_URL` environment variable that may be needed in Docker environments
- Fixes #469 - Docker prebuilt image fails to load models.json
- Verified that `models.json` loads correctly when the `BASE_URL` environment variable is set in a Docker …

feat: add BASE_URL environment variable support for Docker environments

---

components/chat-messages.tsx
components/render-message.tsx

This PR fixes the issue where search results from manual tool calls were not being displayed after the recent changes in PR #473 and #474.
1. Added support for rendering results from `toolData` in `render-message.tsx`, ensuring manual tool call results are displayed.
2. Enhanced the `getIsOpen` function in `chat-messages.tsx` to properly handle tool call IDs, defaulting them to open state.
This fixes issue #476.

fix: display search results from manual tool calls

---

README.md
lib/config/default-models.json
public/config/models.json

- Added Gemini 2.5 Pro (Experimental) model configuration
- Removed deprecated Gemini 2.0 Pro (Experimental) model
- Updated verified models list in README.md
- ID: `gemini-2.5-pro-exp-03-25`
- Name: "Gemini 2.5 Pro (Exp)"
- Provider: Google Generative AI
- Tool Call: Manual (using gemini-2.0-flash as tool call model)
- `public/config/models.json`
- `lib/config/default-models.json`
- `README.md`

Add Gemini 2.5 Pro (Experimental) model

---

components/answer-section.tsx
components/render-message.tsx

Only show actions on the last text part of a message to improve UI clarity.

Only show MessageActions on the last text part

---

.gitignore
components/chat-panel.tsx
components/chat.tsx
components/collapsible-message.tsx
components/related-questions.tsx
components/retrieve-section.tsx
components/search-section.tsx
components/tool-section.tsx
components/video-search-section.tsx

This PR includes two changes to the `CollapsibleMessage` component:
1. **Remove icon space when `showIcon` is false** - Previously, even when `showIcon` was set to false, the space for the icon was still being rendered. This change completely removes the icon column when `showIcon` is false.
2. **Hide icons for non-user/assistant roles** - Added logic to only show icons for 'user' and 'assistant' roles, hiding them for any other roles.
The changes improve the UI by eliminating unnecessary spacing and ensuring consistent icon display behavior.

Remove icon space when showIcon is false

---

components/chat-panel.tsx

This PR adds a welcome message "How can I help you today?" below the logo on the empty chat screen.
Changes:
- Added a bold, large text message below the logo
- Improved styling with better spacing
- Centered the text with the logo
- Adjusted the input field padding for consistency

Add help message to empty chat screen

---

README.md
lib/config/default-models.json
public/config/models.json

This PR adds support for the following new AI models:
- **xAI:**
- Added Grok 3 Beta model with native tool call support
- **Groq:**
- Added Llama 4 Maverick 17B model with native tool call support
- **Fireworks:**
- Added Llama 4 Maverick model with manual tool call support
- Added new model configurations to both `lib/config/default-models.json` and `public/config/models.json`
- Updated the Verified Models section in README.md to reflect the newly added models
Verified that the models appear in the UI model selector.
These models require their respective API keys to be configured in the environment variables as described in the documentation.

Add new AI models

---

components/chat.tsx

This PR adds the `experimental_throttle` option to the `useChat` hook to prevent infinite update loops that were causing the 'Maximum update depth exceeded' error.
The application was experiencing a React error: 'Maximum update depth exceeded'. This occurs when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate, creating an infinite loop.
Added the `experimental_throttle: 100` option to the `useChat` hook configuration to limit update frequency and prevent the infinite loop.

Fix: Add experimental_throttle to useChat to prevent infinite update loops

---

components/chat.tsx

This PR updates the deprecated `useChat` import from `ai/react` to `@ai-sdk/react` and makes the necessary adjustments to work with the new API.
1. Changed the import source for `useChat` from `ai/react` to `@ai-sdk/react`
2. Kept the `Message` import from `ai/react`
3. Updated the API usage:
- The `isLoading` property is no longer directly available from the hook
- Added a derived `isLoading` variable based on the `status` property: `status === 'submitted' || status === 'streaming'`
The `useChat` hook from `ai/react` is deprecated, and the recommended replacement is to use `@ai-sdk/react` instead. This change ensures we're using the current supported version of the hook while maintaining the same functionality.

Fix: Update deprecated useChat import from ai/react to @ai-sdk/react

---

components/chat-messages.tsx
components/chat-panel.tsx
components/chat.tsx
components/question-confirmation.tsx
components/render-message.tsx
components/tool-section.tsx
lib/agents/researcher.ts
lib/streaming/create-tool-calling-stream.ts
lib/tools/question.ts

This PR adds the `ask_question` tool functionality and improves the overall tool UX:
1. Added `ask_question` tool to help the assistant ask clarifying questions when user queries are ambiguous
2. Added input disabling during tool invocation to prevent users from sending messages while tools are running
3. Created question confirmation component to allow users to respond to questions from the assistant
4. Enhanced tool section display and documentation
- Added `ask_question` tool implementation in `lib/tools/question.ts`
- Created question confirmation UI component
- Added `isToolInvocationInProgress()` function to detect active tool invocations
- Disabled input and buttons during tool execution
- Updated documentation and improved tool-related UI elements
The feature was previously …

Add ask_question tool and improve tool UX

---

components/chat-messages.tsx
components/chat-panel.tsx
components/chat.tsx
lib/hooks/use-auto-scroll.ts

This PR adds the ability to cancel auto-scrolling during AI response streaming.
- Created `useAutoScroll` hook to manage auto-scrolling behavior
- Added user scroll detection to pause auto-scrolling when user scrolls away
- Added a scroll-down button that appears when the user has scrolled away from the bottom
- Auto-scrolling automatically resumes when user returns to the bottom of the conversation
- Created a reusable hook in `lib/hooks/use-auto-scroll.ts`
- Moved auto-scroll management to parent `Chat` component
- Added user scroll detection with scroll events
- Added conditional ChevronDown button in ChatPanel for manual scrolling
This improves UX by allowing users to pause streaming content to read earlier messages without fighting the auto-scroll, while still providing an easy way …

Add scroll cancelation during AI response streaming

---

components/answer-section.tsx
components/chat-messages.tsx
components/chat.tsx
components/message-actions.tsx
components/render-message.tsx
components/retry-button.tsx

This PR adds the ability to retry responses from any point in the conversation. When users click the retry button on an assistant message, the conversation is regenerated from the user message that preceded it.
- Added retry button to assistant messages
- Implemented message-specific retry functionality
- Created a reusable RetryButton component
- Enhanced state management to support conversation regeneration
- Added `handleReloadFrom` function to the Chat component that:
- Trims messages to the selected point in the conversation
- Uses the `reload` function from the `useChat` hook to regenerate the conversation
- Created a proper prop-passing chain from Chat down to MessageActions
- Implemented a standalone RetryButton component with clear visual indication
1. Start a conversation with …

Add message retry functionality

---

lib/utils/registry.ts

This PR addresses issue #498 by updating the Azure OpenAI API version to `2025-03-01-preview`.
The current default Azure OpenAI API version (`2024-10-01-preview`) is too old to support newer models like o3-mini, resulting in errors when attempting to use these models.
- Updated the API version to `2025-03-01-preview` in the Azure OpenAI provider initialization
- This change enables support for newer models without requiring per-model configuration
- Confirmed the change allows the use of newer Azure OpenAI models such as o3-mini
- Verified existing Azure OpenAI functionality continues to work with the updated API version
Fixes #498

Fix: Update Azure OpenAI API version to support newer models

---

lib/agents/researcher.ts
lib/schema/question.ts
lib/schema/search.tsx
lib/tools/question.ts
lib/tools/search.ts
lib/tools/video-search.ts

This PR fixes an issue with Vercel AI SDK's handling of OpenAI and Azure models whose names start with 'o' (such as o3-mini), which require non-optional parameters in their schema.
- Added new schema selection mechanism for tool parameters
- Created strict schemas (no optional fields) for o-prefix models
- Added helper functions to dynamically select schema based on model provider and name
- Updated researcher.ts to use model-specific tool creation
- Added `strictQuestionSchema` and `strictSearchSchema` with required fields
- Created helper functions that select schema based on model string:
- `getQuestionSchemaForModel(fullModel)`
- `getSearchSchemaForModel(fullModel)`
- Added factory functions for tools that use the appropriate schema:
- `createQuestionTool(fullModel)`
- …

Fix schema selection for o-prefix models in OpenAI and Azure providers

---

app/api/chats/route.ts
components/sidebar/chat-history-client.tsx
components/sidebar/chat-history-section.tsx
lib/actions/chat.ts

This PR addresses task #3 from the v0.4 Roadmap (issue #501): "Improve the chat history component".
- Added paginated chat history with infinite scroll:
- Created new `getChatsPage` server action that supports pagination with limit/offset
- Implemented `/api/chats` endpoint to fetch pages of chat history
- Refactored sidebar history into server wrapper + client component architecture
- Added intersection observer to detect scroll position and load more items
- Added effect to synchronize props to state when new chats are created
- Improvements:
- Initial load limited to 20 chats (vs. all chats previously)
- Infinite scroll automatically loads next 20 chats when user scrolls to bottom
- Memory usage is optimized by loading only what's needed
- Fixes issue with new chats not appearing in …

Improve chat history with pagination and infinite scroll

---

app/api/chat/[id]/route.ts
components/sidebar/chat-menu-item.tsx
components/ui/spinner.tsx
lib/actions/chat.ts

This PR adds the ability to delete individual chat items from the history sidebar, enhancing the user experience by providing more granular control over chat history management.
- Added `deleteChat` server action to support deleting a single chat
- Implemented `/api/chat/[id]` endpoint with DELETE method for API-based removal
- Added dropdown menu with delete option to each chat history item
- Integrated confirmation dialog to prevent accidental deletions
- Supports proper error handling and feedback via toast notifications
- Manages loading states with spinners during deletion process
- Updated `Spinner` component to support className prop for better styling
- Each chat now has a kebab menu (three dots) on hover
- Clicking delete shows a confirmation dialog similar to "Clear History"
- …

Add individual chat delete action with confirmation dialog

---

.cursor/rules/create-db-functions.mdc
.cursor/rules/create-migration.mdc
.cursor/rules/create-rls-policies.mdc
.cursor/rules/postgres-sql-style-guide.mdc
.cursor/rules/writing-supabase-edge-functions.mdc

This PR adds Supabase rules for AI editor support.
Added 5 new files:
- `.cursor/rules/create-db-functions.mdc`: Guidelines for writing Supabase database functions
- `.cursor/rules/create-migration.mdc`: Guidelines for writing Postgres migrations
- `.cursor/rules/create-rls-policies.mdc`: Guidelines for writing Postgres Row Level Security policies
- `.cursor/rules/postgres-sql-style-guide.mdc`: Guidelines for writing Postgres SQL
- `.cursor/rules/writing-supabase-edge-functions.mdc`: Coding rules for Supabase Edge Functions
These rules were added using the shadcn command:
```
bunx --bun shadcn@latest add https://supabase.com/ui/r/ai-editor-rules.json
```

Add Supabase rules for AI editor

---

app/api/chat/[id]/route.ts
app/api/chat/route.ts
app/api/chats/route.ts
app/search/[id]/page.tsx
components/sidebar/chat-history-section.tsx
lib/auth/get-current-user.ts
lib/streaming/create-manual-tool-stream.ts
lib/streaming/create-tool-calling-stream.ts
lib/streaming/handle-stream-finish.ts
lib/streaming/types.ts

This PR integrates Supabase authentication with the chat history feature.
Changes:
- Modified chat actions (`getChat`, `saveChat`, `getChatsPage`, `deleteChat`) to use the authenticated user's Supabase ID (`user.id`) instead of a hardcoded 'anonymous' ID.
- Guest users continue to use the 'anonymous' ID for their chats.
- Created a new helper function `lib/auth/get-current-user.ts` to securely fetch the current user's ID on the server-side using session cookies.
- Updated relevant API routes (`/api/chat`, `/api/chat/[id]`, `/api/chats`) to use the new helper function.
- Updated server components (`ChatHistorySection`, `SearchPage`) to fetch and pass the user ID.
- Updated streaming logic (`handleStreamFinish`, `createToolCallingStreamResponse`, `createManualToolStreamResponse`, …

feat: Integrate Supabase user ID with chat history

---

components/search-mode-toggle.tsx

This PR addresses issue #470.
Previously, the search-mode cookie was not set on initial page load if it didn't already exist. This caused an inconsistency between the UI (showing search as active by default) and the actual cookie state, leading to the first search attempt failing.
This change modifies the `SearchModeToggle` component to set the 'search-mode' cookie to 'true' in `useEffect` if the cookie is not found, ensuring the UI state and cookie state are synchronized from the beginning.

Fix: Ensure search-mode cookie is set on initial load

---

bun.lock
components/collapsible-message.tsx
components/current-user-avatar.tsx
components/ui/avatar.tsx
hooks/use-current-user-image.ts
hooks/use-current-user-name.ts
package.json

This PR implements the display of user avatars in chat messages.
Key changes:
- Integrated Supabase UI's `CurrentUserAvatar` component.
- Modified `CollapsibleMessage` to use `CurrentUserAvatar` for user messages.
- Customized the fallback behavior of `CurrentUserAvatar` to display a `User2` icon when the user's name is not available (resulting in '?').

feat: Display user avatar in chat messages

---

app/layout.tsx
lib/auth/get-current-user.ts
middleware.ts

This PR addresses issue #518 by preventing the application from attempting to initialize the Supabase client when the necessary environment variables (NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY) are not defined.
Changes were made in:
- `middleware.ts`: Conditionally calls `updateSession`.
- `app/layout.tsx`: Conditionally creates a Supabase client and fetches user data.
- `lib/auth/get-current-user.ts`: The `getCurrentUser` function now checks for Supabase environment variables before attempting to create a client, returning `null` if they are not set. This allows `getCurrentUserId` to return 'anonymous' and dependent components like `ChatHistorySection` to handle this state gracefully.

Fix: Prevent Supabase client initialization errors when env vars are missing

---

components/chat-messages.tsx
components/chat.tsx
lib/hooks/use-auto-scroll.ts

This PR addresses issue #516 (I cant scroll when stream message) by implementing the following changes:
- **Improved Auto-Scroll Cancellation:** Refined the `useAutoScroll` hook to reliably cancel auto-scrolling when the user manually scrolls up during message streaming. This was achieved by:
- Synchronously detecting user scroll within `handleScroll`.
- Using a `useRef` (`autoScrollIsEnabledRef`) to immediately reflect and check the auto-scroll state, preventing race conditions with ongoing `scrollToBottom` calls.
- Ensuring scroll event listeners are correctly attached to the scroll container even if it's initially null.
- **Consolidated "Scroll to Bottom" Button:** Removed the duplicate "Scroll to bottom" button from `ChatMessages` and kept the one in `ChatPanel` as the single source …

Fix: Streaming scroll cancellation and button consolidation for issue #516

---

bun.lock
lib/actions/__tests__/chat-db.test.ts
package.json
tsconfig.json
vitest.config.ts
vitest.setup.ts

- Added Vitest test framework setup with jsdom environment
- Created comprehensive unit tests for `lib/actions/chat-db.ts` covering all exported functions
- Tests include positive test cases as well as failure paths and edge cases
- Added utility to handle environment variables during testing
- Added npm scripts for running tests
- All tests pass successfully
- Mock implementation approach used for DB and auth dependencies
- Test coverage includes error handling, authentication flows, and complex permission logic

Add unit tests for lib/actions/chat-db.ts with Vitest

---

components/chat-messages.tsx
components/reasoning-section.tsx
components/render-message.tsx
components/ui/status-indicator.tsx

This PR simplifies the reasoning section and cleans up message rendering:
1. Simplified the reasoning section:
- Replaced time-based indicators with a simple isDone boolean
- Updated status indicator to show only completion state
- Removed character count display
2. Cleaned up render-message.tsx:
- Removed unused toolData and related questions code
- Simplified message part rendering
- Improved code organization
3. Made StatusIndicator component more flexible:
- Made children prop optional
- Added proper type checking
4. Minor cleanup in chat-messages.tsx
These changes make the code more maintainable and improve the user experience by simplifying the reasoning section display.

Simplify reasoning section and cleanup message rendering

---

components/chat-messages.tsx
lib/agents/title-generator.ts
lib/streaming/create-tool-calling-stream.ts
lib/utils/message-utils.ts

This PR enhances the chat title generation by using an LLM instead of simply taking the user's first message as the title. The feature creates concise, descriptive titles for new chat sessions.
- Created a new `generateChatTitle` function in `lib/agents/title-generator.ts` that uses the Vercel AI SDK's `generateText` function to generate chat titles.
- The function takes the user's message content and a language model, then returns a concise (3-5 words) title.
- Updated `lib/streaming/create-tool-calling-stream.ts` to use this new function for title generation when creating new chats.
- Modified the `getTextFromParts` function usage to correctly extract text content from message parts.
- More meaningful and concise chat titles
- Better organization of chat history
- Improved user …

Enhance chat title generation using LLM

---

lib/tools/search.ts
lib/tools/search/providers/base.ts
lib/tools/search/providers/exa.ts
lib/tools/search/providers/index.ts
lib/tools/search/providers/searxng.ts
lib/tools/search/providers/tavily.ts

There are many good reasons to split the provider logic out into separate files. First, it makes it easier to add new providers. Second, for those of us getting help from copilots, it makes their performance better. Finally, the logic is easier to follow.
The searchprovider logic in lib/tools/search/providers/index.ts implements a factory pattern for managing search providers in this search engine:
Architecture
- Uses a plugin architecture with a common interface and specialized implementations
- Providers include Tavily, Exa, and SearXNG, all extending a BaseSearchProvider
- Factory function createSearchProvider(type?) instantiates the appropriate provider
- Provider selection controlled via parameters, environment variables, or defaults to 'tavily'
Key Features
- All providers implement …

Refactor search.ts:

---

lib/config/models.ts
lib/tools/search.ts
middleware.ts

Make baseUrl dynamic.
Updated middleware.ts to:
- Extract protocol and host from request headers
- Construct a dynamic base URL
- Add this information to response headers
- Preserve existing Supabase session functionality
Modified lib/config/models.ts to:
- Export the getBaseUrlFromHeaders() function
- Check for NEXT_PUBLIC_BASE_URL first as an override
- Fall back to dynamically determined base URL from headers
Updated lib/tools/search.ts to:
- Import and use the getBaseUrlFromHeaders() function
- Dynamically determine the base URL when NEXT_PUBLIC_BASE_URL isn't set
The development server can now run on any port (eg. 3001), confirming that the system can automatically adapt to different ports without manual configuration. This makes the application more flexible when deployed in various …

A middleware-based approach for base URL determination

---

app/api/chat/route.ts
lib/agents/researcher.ts
lib/streaming/create-chat-stream-response.ts
lib/streaming/create-tool-calling-stream.ts

This PR includes the following refactorings:
- Renamed `createToolCallingStreamResponse` to `createChatStreamResponse`.
- Updated authentication logic in `createChatStreamResponse` to return a 403 error for unauthorized access.
- Modified the `researcher` function to return the `streamText` result directly, simplifying its usage.

Refactor chat streaming and researcher logic

---

bun.lock
lib/agents/generate-related-questions.ts
lib/agents/researcher.ts
lib/agents/title-generator.ts
lib/streaming/create-chat-stream-response.ts
lib/utils/registry.ts
package.json

This PR standardizes model references across agent files to use the `getModel` function consistently. As part of this change, the Ollama AI provider has been removed since it does not support languageModelV2.
- Updated agent files to consistently use `getModel` function instead of direct model references:
- Updated `lib/agents/researcher.ts`
- Updated `lib/agents/generate-related-questions.ts`
- Updated `lib/agents/title-generator.ts`
- Removed Ollama-specific code from `lib/utils/registry.ts`
- Removed `ollama-ai-provider` package from dependencies
These changes ensure consistency in how models are accessed throughout the application while supporting the transition to languageModelV2.

Standardize Model References Using getModel Function

---

components/chat-panel.tsx
components/uploaded-file-list.tsx

This PR improves the uploaded file component layout with the following changes:
1. Renamed the component file from `uploaded-fileList.tsx` to `uploaded-file-list.tsx` following kebab-case convention
2. Modified layout styling:
- Changed container from `justify-center` to centered with `max-w-3xl mx-auto`
- Adjusted the width of file items from `w-28` to `w-20`
- Changed container padding from `py-4` to `p-4`
- Modified aspect ratio for thumbnails using `aspect-[7/5]` instead of fixed height
These changes improve the overall appearance and consistency of the uploaded file list.

Improve uploaded file component layout and rename to kebab-case

---

components/chat-messages.tsx
components/message-actions.tsx
components/related-questions.tsx
components/render-message.tsx

Refactored the chat messages component to implement improved auto-collapse behavior for reasoning components.
- Reasoning components now auto-collapse when there's a next part in the same message
- Preserve user-modified states when users explicitly open/close components
- Replace `openStates` management with `userModifiedStates` for better state tracking
- Simplify `getIsOpen` function parameters and remove unused `sectionIndex`
- Clean up prop passing and function references
- Remove debugging console.log statements
- **Reasoning**: Auto-collapses when there's a next part in the same message, but respects user's explicit open/close actions
- **Tool invocations**: Default to open state
- **Text**: Default to open state
- Updated `getIsOpen` function signature to accept `partType` and …

refactor: improve reasoning auto-collapse logic in chat messages

---

app/search/[id]/page.tsx

This corrects the implementation for dynamic Open Graph (OG) images for your search result pages (`/search/[id]`) as per issue #536 and your subsequent feedback.
The `og:image` meta tag will now point to an actual image URL retrieved from the search results, rather than generating a new image card.
Key changes:
- I modified the `generateMetadata` function in `app/search/[id]/page.tsx`:
- It now fetches chat data, looking for a 'data' message containing search results (images and web results).
- It extracts the first image URL from the `images` array within the search results.
- This URL is set as the `og:image` in the page's metadata, including standard width (1200) and height (630).
- If no image is found in the search data or an error occurs, the `og:image` tag is not set by this …

feat: Use image from search results for OG tag

---

app/api/chat/route.ts
app/search/loading.tsx
components/chat.tsx
lib/streaming/create-chat-stream-response.ts

This PR fixes the reload and edit functionality to use messageId-based operations instead of timestamp-based operations, making the implementation more reliable and aligned with Vercel AI SDK v5 patterns.
- Updated `handleUpdateAndReloadMessage` to edit messages in-place without creating duplicates
- Simplified `handleReloadFrom` to use the SDK's built-in `regenerate` function
- Modified `prepareSendMessagesRequest` to include edited user messages during regeneration
- Updated API route to properly handle message objects instead of arrays
- Enhanced stream handler to save edited messages before regeneration
- Improved regeneration logic to handle both assistant and user message regeneration
- **No more createdAt dependency**: All operations now use messageId for precision
- **Fixed …

Fix reload and edit functionality with messageId-based operations

---

lib/actions/chat.ts
lib/streaming/create-chat-stream-response.ts
lib/streaming/message-preparation.ts
lib/utils/message-utils.ts

- Skip related questions generation when the AI provides direct answers without using any tools
- Improve response time for simple queries that don't require tool usage
- Refactor code to move logic outside of onFinish callback for better readability
1. **Feature Implementation**
- Add logic to detect if response contains tool calls (parts with type 'tool-*' or 'tool-call')
- Skip related questions and finish stream immediately for direct answers
- Maintain all existing functionality for responses with tool calls
2. **Code Refactoring**
- Move helper functions to appropriate modules:
- `hasToolCalls()` → `/lib/utils/message-utils.ts`
- `saveChatTitle()` → `/lib/actions/chat.ts`
- Create `/lib/streaming/message-preparation.ts` for message prep logic
- Refactor to use Promise wrappers …

feat: skip related questions generation when no tool calls

---

lib/agents/generate-related-questions.ts
lib/db/actions.ts
lib/streaming/create-chat-stream-response.ts
lib/utils/__tests__/anthropic-message-conversion.test.ts
lib/utils/anthropic-message-conversion.ts
lib/utils/message-mapping.ts
lib/utils/model-detection.ts

This PR fixes an issue where Anthropic models would fail on the second chat message with the error: "tool_use ids were found without tool_result blocks immediately after".
When messages were loaded from the database, the `convertToModelMessages` function was creating a single assistant message containing all parts (text, tool-call, text). However, the AI SDK expects tool-call to be immediately followed by tool-result in separate messages.
1. Updated `mapDBPartToUIMessagePart` in `message-mapping.ts` to properly handle tool parts according to their state, following the official AI SDK sample pattern
2. Created `convertMessagesForAnthropic` helper function that fixes message structure after `convertToModelMessages` by splitting assistant messages that contain text after tool-call parts
3. …

Fix Anthropic model message structure for tool-call/tool-result separation

---

lib/config/default-models.json
public/config/models.json

This PR updates the model configurations to include the newly released GPT-5 series models from OpenAI.
- Replaced GPT-4.1 with three new GPT-5 models in both `/public/config/models.json` and `/lib/config/default-models.json`:
- `gpt-5-2025-08-07` (GPT-5)
- `gpt-5-mini-2025-08-07` (GPT-5 Mini)  
- `gpt-5-nano-2025-08-07` (GPT-5 Nano)
There is a known issue with reasoning display for these new GPT-5 models. This issue is already being tracked in the Vercel AI SDK repository: https://github.com/vercel/ai/issues/7861
The model configurations have been updated consistently across both configuration files to ensure proper functionality.

Update OpenAI models to GPT-5 series

---

components/collapsible-message.tsx
components/search-section.tsx
components/section.tsx

This PR fixes text overflow issues in search section headers where long query text would break the layout by overflowing beyond container boundaries.
1. **`components/collapsible-message.tsx`** - Added `overflow-hidden` to container and header div to properly constrain content
2. **`components/search-section.tsx`** - Added `overflow-hidden` to the button wrapper
3. **`components/section.tsx`** - Added `overflow-hidden` to ToolArgsSection and its inner div
When users performed searches with very long queries (like "NVIDIA growth drivers AI data center demand 2024 2025 revenue data center GPU market share CUDA ecosystem software..."), the text would overflow beyond its container boundaries, breaking the layout.
Added `overflow-hidden` CSS classes to the appropriate container elements. This …

Fix text overflow in search section headers

---

components/render-message.tsx

This PR fixes the message actions display logic to ensure actions (copy, thumbs up/down, share) appear only on the last text part of each assistant message.
Previously, message actions were appearing on all assistant messages in a conversation thread, even during streaming. The logic was based on whether a message was the latest in the entire conversation, rather than checking individual message parts.
- Modified the logic to detect the last text part within each message
- Actions now appear only on the last text part of each assistant message
- For the latest message, actions are hidden during streaming and shown only after completion
- For completed messages, actions are always visible on their last text part
- Updated  to check for the last text part within each message using 
- …

Fix: Display message actions only on last text part

---

lib/agents/prompts/search-mode-prompts.ts

This PR addresses #682 by strengthening prompt instructions (no system-level enforcement):
Changes:
- Planning mode: require a todoRead verification (completedCount == totalCount) before composing the final answer.
- Adaptive mode: add an explicit task loop (pending → in_progress → completed) and verification step.
- Clarify progress updates and status transitions using todoWrite during execution.
Rationale:
- Keeps control at the prompt level as requested; avoids hard-coded stop conditions.
- Encourages the model to maintain and verify the TODO list it creates, reducing early finalization.
Notes:
- Quick mode is unchanged (still optimized for speed without task tracking).
- Behavior still depends on model capabilities; this improves compliance without over-constraining.
Refs #682

docs(prompt): enforce TODO completion via prompts (Refs #682)

---

lib/actions/chat.ts
lib/streaming/helpers/prepare-messages.ts
lib/streaming/message-preparation.ts

- ensure deleteMessagesFromIndex always runs with the current user context so RLS queries succeed
- allow streaming regenerate flow to pass through the user id when removing stale assistant replies
- regenerate assistant messages in browser without encountering "No messages deleted" errors

Fix assistant message deletion under RLS

---

app/api/chat/route.ts
lib/agents/title-generator.ts
lib/streaming/create-chat-stream-response.ts
lib/streaming/helpers/persist-stream-results.ts
lib/streaming/helpers/prepare-messages.ts
lib/streaming/helpers/types.ts

- start chat streaming without waiting for initial chat persistence by running createChatWithFirstMessage in the background
- pipe pending persistence context through the streaming stack and await it before persisting the assistant response, including fallback handling
- soften title-generation logging when aborting to avoid noisy errors
- bun lint

feat: start chat streaming optimistically

---

components/search-results-image.tsx

- normalize incoming search images and preload them on the client
- expose `useFilteredImages` to drop invalid URLs and keep placeholders scoped to loading state
- centralize embla bookkeeping in `useCarouselMetrics` for cleaner current/count handling

refactor: streamline search image filtering

---

components/related-questions.tsx
lib/agents/generate-related-questions.ts
lib/schema/related.tsx
lib/streaming/helpers/stream-related-questions.ts
lib/types/ai.ts

- switch related questions generator to use streamObject for array streaming
- emit incremental data-relatedQuestions payloads as each question arrives
- update schema, types, and UI to handle streaming status and placeholders

Stream related questions incrementally

---

app/api/config/models/route.ts
app/api/ollama/models/route.ts
lib/config/models.ts
lib/ollama/client.ts
lib/ollama/transformer.ts
lib/ollama/types.ts
lib/types/models.ts
lib/utils/registry.ts

Add dynamic Ollama model discovery that fetches models from running Ollama instance and filters them based on "tools" capability for websearch-capabilities.. 
This includes new API endpoints and extends model interface
**In detail:** 
- Add OllamaClient for API integration with /api/tags and /api/show endpoints
- Implement dynamic model discovery with tools capability detection
- Add /api/ollama/models and /api/config/models endpoints
- Extend Model interface with capabilities and contextWindow fields
- Update registry to support Ollama tool calling
- Filter models to only include those with tools capability
- Merge static and Ollama models in unified endpoint"
**Screenshot of using morphic with a Ollama Server with several models:** 
(Models without "tools" capabilities are automatically …

feat: integrate Ollama model discovery with tools filtering

---

app/globals.css
components/chat-messages.tsx
components/search-results-image.tsx
components/section.tsx

- keep single tool results expanded by default
- prevent image preview flicker by reusing preloaded data
- switch Sources badge to FileText icon for a lighter look
- bun run lint
- bun run typecheck
- bun run format:check

Keep single tool sections open and stabilize image previews
