miurla/morphic

components/collapsible-message.tsx, components/followup-panel.tsx
Show follow-up panel when the last message is collapsed
=> Add FollowupPanel component to CollapsibleMessage

components/collapsible-message.tsx, components/followup-panel.tsx
=> Revert "Add FollowupPanel component to CollapsibleMessage"

README.md
Reverts miurla/morphic#56
A contributor added this, but I’ve never used this service and cannot support it.
If an alternative is needed, we'll reconsider it.
=> Revert "Adding additional deploy option to README.md"

app/page.tsx
=> Remove unnecessary `use client`

.env.local.example, README.md
If the Provider is set to Anthropic, an error occurs, so temporarily remove it from the configuration.
https://github.com/miurla/morphic/issues/83
=> Temporarily, remove specific provider configuration.

components/chat-panel.tsx
closes: #88 
Remove unnecessary codes
=> Refactor form position in ChatPanel component

README.md, app/actions.tsx, app/page.tsx, app/search/[id]/page.tsx, app/share/[id]/page.tsx, components/chat-share.tsx, components/chat.tsx, components/collapsible-message.tsx, components/copilot-display.tsx, components/user-message.tsx, lib/actions/chat.ts, lib/hooks/use-copy-to-clipboard.ts
=> Enable sharing of search results

components/chat-share.tsx
This PR addresses an issue where Safari throws an Unhandled Promise Rejection: NotAllowedError when attempting to copy a link to the clipboard. This error occurs because Safari requires clipboard operations to be directly triggered by user interactions. Our previous implementation attempted to copy to the clipboard after an asynchronous server action, which Safari does not recognize as a direct user interaction.
=> Fix handle sharing and copying chat links

app/actions.tsx
closes: #152 
All messages were passed to the writer.
=> Refactor submit function to use latest messages

components/chat-panel.tsx
returned from the function when there is not input value
=> prevented search submit when no input value

.env.local.example, README.md, app/actions.tsx, components/section.tsx, components/video-search-results.tsx, components/video-search-section.tsx, lib/agents/researcher.tsx, lib/agents/tools/index.tsx, lib/agents/tools/retrieve.tsx, lib/agents/tools/search.tsx, lib/agents/tools/video-search.tsx, lib/types/index.ts
This pull request adds a video search feature to the application. It closes issue #61.
- Implement a video search tool
- Add a video search API integration
- Create a video section component
- Enable video control within a modal
The Serper API Key must be set in the environment variables for the video search functionality to work.
=> Add Video Search Feature

components/message.tsx
=> Refactor component to render LaTeX equations if patterns are found

components/chat-panel.tsx
I checked the state `isButtonPressed`, it was never being set to `true`, so the logic is staying unused
If you want to build some logic with the state, let me know
=> removed unused state and logic

app/actions.tsx, components/chat-messages.tsx, components/chat-panel.tsx, components/search-results-image.tsx, components/search-results.tsx, lib/types/index.ts
- Removed any types
- Added types where needed
- Minor code optimisation
=> removed any types where possible

lib/agents/writer.tsx
closes: #178 
Due to the changes in #161, the writer's model was also using a unified model.
=> Update writer.tsx to use OpenAI SDK

app/actions.tsx, components/search-results.tsx, components/user-message.tsx, lib/agents/researcher.tsx, lib/agents/tools/retrieve.tsx, lib/agents/writer.tsx
=> Fix error handling in submit and writer functions

README.md, app/search/page.tsx, components/chat-panel.tsx, components/chat.tsx
=> Use as a search engine

app/actions.tsx, components/chat.tsx, components/history-container.tsx, components/history-list.tsx, components/history-skelton.tsx, components/history.tsx, components/sidebar.tsx
closes: #186
Changed the timing of updating the history from the end of generation to when the user opens the history.
=> Refactor chat component and history container

app/actions.tsx, components/error-card.tsx, lib/agents/tools/retrieve.tsx, lib/agents/tools/search.tsx, lib/agents/tools/video-search.tsx
=> Update submit function to handle error cases and retry

app/actions.tsx, lib/agents/writer.tsx
Fixed an issue where the text stream could not be closed due to changes in #208.
=> fix: Close the text stream

components/search-section.tsx, lib/agents/researcher.tsx, lib/agents/tools/search.tsx, lib/schema/search.tsx
=> feat: Add support for including and excluding domains in search results

lib/agents/writer.tsx, lib/utils/index.ts
Deprecated:
Use baseURL instead.
=> baseUrl is deprecates, use baseURL

README.md
URL in the README was heading towards local repo and not morphic.sh
=> fixed morphic.sh url

components/chat.tsx
=> fix: Update Chat component to fix search path condition

components/chat.tsx, components/search-related.tsx
=> Fix search path condition

.env.local.example
Updated: `OPENAI_API_MODEL=gpt-4o-mini`
=> Update the value of OPENAI_API_MODEL in env.local.example

components/copilot.tsx, components/followup-panel.tsx
closes: #262 
Fixed to check the isGenerating status when sending messages.
=> Prevent messages from being sent multiple times

.env.local.example, README.md
- llama-3.1-8b-instant
- llama-3.1-70b-versatile
=> Add LLaMA3.1 models to the verified models list

lib/agents/tools/search.tsx, lib/utils/index.ts
closes: #283 
Fixed to sanitize image URLs from the search API.
=> Sanitize image URLs in searchTool

README.md
=> chore: Modify README to include instructions for local Redis setup

lib/utils/index.ts
=> Enhance AI provider validation to include Azure OpenAI

.env.local.example, README.md, app/actions.tsx, lib/actions/workflow.tsx, lib/agents/query-suggestor.tsx, lib/agents/researcher.tsx, lib/agents/tools/search.tsx, lib/schema/search.tsx
As object generation and Tool usage with Ollama are now working stably, modify to make them work in Morphic
- Extract ProcessEvent as a workflow 
- Add an ollama workflow
- Currently compatible model: `qwen2.5`
- Ollama currently does not support tool streaming. Therefore, there is a waiting time until the answer is generated
https://github.com/sgomez/ollama-ai-provider
=> feat: Improve Ollama support

.env.local.example, README.md, components/empty-screen.tsx, lib/agents/tools/retrieve.tsx
=> feat: Support Tavily extract API

README.md
- AI SDK RSC: https://sdk.vercel.ai/docs/getting-started/navigating-the-library#when-to-use-ai-sdk-rsc
- Discussion: https://github.com/vercel/ai/discussions/3251
=> Update README with warning

components/default-skeleton.tsx, lib/actions/workflow.tsx, lib/agents/tools/search.tsx
closes: #366 
- Search results were updating
=> Fix display of multiple tool calls

.env.local.example, components/chat-panel.tsx, lib/types/models.ts, lib/utils/registry.ts, public/providers/logos/openai-compatible.svg
Add OpenAI compatible model to model selection
Set the following environment variables to enable
```
NEXT_PUBLIC_OPENAI_COMPATIBLE_MODEL=[YOUR_OPENAI_COMPATIBLE_MODEL]
OPENAI_COMPATIBLE_API_KEY=[YOUR_OPENAI_COMPATIBLE_API_KEY]
OPENAI_COMPATIBLE_API_BASE_URL=[YOUR_OPENAI_COMPATIBLE_API_BASE_URL]
```
=> feat: Support OpenAI compatible model

lib/types/models.ts
Claude 3.5 Haiku: https://www.anthropic.com/claude/haiku
=> feat: Add support for Claude 3.5 Haiku model

.env.local.example, lib/types/models.ts
fix: https://github.com/miurla/morphic/issues/378#issuecomment-2513337179
Fix to make Azure deployment name configurable through environment variables instead of being hardcoded
=> fix: Make Azure deployment name configurable through environment vars

README.md, lib/types/models.ts
This pull request includes several updates to the `README.md` file and an addition to the `lib/types/models.ts` file. The changes primarily focus on improving URL formatting and adding new models. Below are the most important changes:
* Updated URL formatting in `README.md` to use angle brackets for better readability. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L129-R137) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L173-R174) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L197-R197) [[4]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L223-R236)
* Added a new experimental model, `Gemini 2.0 Flash`, to the `models` array in …
=> chore: Update README and models to include formatted URLs and add Gemini 2.0 Flash model

app/api/chat/route.ts, app/layout.tsx, app/page.tsx, app/search/[id]/page.tsx, app/search/page.tsx, app/share/[id]/page.tsx, components/chat.tsx, components/related-questions.tsx, lib/actions/chat.ts, lib/types/index.ts
=> feat: save chat with related questions after completion

components/chat-messages.tsx, components/render-message.tsx
=> refactor: unify message rendering pattern for tools and annotations

components/chat-panel.tsx, components/chat.tsx, components/empty-screen.tsx, components/model-selector.tsx
- Move model selector and buttons to bottom menu
- Increase textarea default height
- Update new chat button position and icon
- Clean up unnecessary styles
=> refactor: improve chat input design

README.md, lib/schema/search.tsx, lib/streaming/create-tool-calling-stream.ts, lib/types/models.ts, lib/utils/registry.ts
=> feat: add support for o3-mini model

README.md, lib/types/models.ts, lib/utils/registry.ts
Due to instability in Gemini's native tool calling functionality, we have switched to a manual tool calling implementation. 
Changes include:
- Updated Gemini 1.5 Pro to Gemini 2.0 Pro (Exp)
- Gemini 2.0 Flash:
- Gemini 2.0 Flash Thinking (Exp)
- Gemini 2.0 Flash (stable)
close: #425
=> feat(models): update Gemini models

components/reasoning-answer-section.tsx, components/render-message.tsx, lib/streaming/create-manual-tool-stream.ts, lib/utils/index.ts
=> feat: add reasoning timing measurement and include elapsed time

.github/workflows/docker-build.yml
- Add linux/arm64 platform support
- Enable buildx for multi-platform builds
- Support for M1/M2 Macs
=> feat: add multi-architecture Docker build support

Dockerfile
fix: #435 
- Update to latest Bun image
- Fix TextEncoderStream error in production
=> fix: update Docker configuration

.env.local.example, app/layout.tsx, components/history-container.tsx
- Remove NEXT_PUBLIC_ prefix as it is not used in client components
- Update variable name in layout.tsx and history-container.tsx
- Update .env.local.example
=> refactor: rename NEXT_PUBLIC_ENABLE_SAVE_CHAT_HISTORY to ENABLE_SAVE_CHAT_HISTORY

public/config/models.json
=> Add Claude 3.7 Sonnet to models.json

app/layout.tsx, components/header.tsx, components/history-container.tsx, components/history.tsx, components/sidebar.tsx
- Remove sidebar component from layout
- Adjust header responsive design
- Simplify history components by removing location-specific logic
- Create consistent navigation experience across all device sizes
=> feat: Unify navigation in header for all devices

lib/streaming/handle-stream-finish.ts
from NEXT_PUBLIC_ENABLE_SAVE_CHAT_HISTORY to ENABLE_SAVE_CHAT_HISTORY
=> Fix: Change environment variable 

components/answer-section.tsx, components/collapsible-message.tsx, components/related-questions.tsx, components/section.tsx
This PR includes several UI layout improvements:
1. Remove unnecessary gap in CollapsibleMessage component
2. Add showIcon=false to AnswerSection component
3. Refactor RelatedQuestions component for better layout
4. Simplify Section component title styling
These changes result in a cleaner, more consistent UI with better spacing throughout the application.
=> Clean up UI layout for collapsible message components

components/chat-messages.tsx, components/chat.tsx, lib/agents/manual-researcher.ts, lib/agents/researcher.ts
This PR adds continuous scrolling during message streaming to improve user experience.
- Added interval-based auto-scrolling during streaming
- Optimized scroll behavior based on message count
- Ensures users always see the latest content during AI responses
=> Add continuous scrolling during message streaming

app/layout.tsx, components/chat-messages.tsx, components/chat-panel.tsx, components/chat.tsx, components/related-questions.tsx, lib/hooks/use-auto-scroll.ts
This PR improves the chat layout and fixes scrolling issues:
- Refactored layout structure to use proper flex containers
- Replaced position:fixed with flex-based positioning for better mobile compatibility
- Implemented responsive container sizing with max-width constraints
- Added proper scroll container with optimized performance (contain: strict)
- Applied mobile-first design principles
- Fixed scroll button flickering during streaming responses
- Improved scroll detection logic for better UX
- Moved scroll button to a consistent position in the UI
- Adjusted scroll sensitivity for more intuitive user control
- Removed fixed positioning from header for better layout integration
- Integrated header into the flex layout system
- Removed redundant padding used to accommodate fixed …
=> Improve chat layout and fix scroll behavior

components/chat.tsx, components/clear-history.tsx, components/sidebar/chat-history-client.tsx, components/sidebar/chat-history-section.tsx, components/sidebar/chat-menu-item.tsx, components/sidebar/clear-history-action.tsx, components/ui/sidebar.tsx
Closes #524
This PR refactors the chat history functionality to be primarily client-side, addressing issues caused by server component re-renders.
**Original Problem:**
Updating the chat history (e.g., after a new chat completion or clearing history) involved `router.replace()` followed by `router.refresh()`. Since the chat history section was a Server Component, `router.refresh()` triggered a full re-render of this section. This led to the loss of scroll position and other UI state, negatively impacting the user experience.
**Solution Implemented:**
- The `ChatHistoryClient` component, responsible for displaying the chat history, now manages its state and data fetching entirely on the client-side. It fetches initial data on mount and subsequently uses an infinite scrolling mechanism.
- …
=> Refactor: Client-side Chat History to Preserve Scroll and Prevent Re-renders

components/chat.tsx
As per https://github.com/miurla/morphic/pull/543
=> Update react warnings 

components/chat.tsx, components/related-questions.tsx, components/render-message.tsx, components/tool-section.tsx, lib/agents/generate-related-questions.ts, lib/schema/related.tsx, lib/streaming/create-chat-stream-response.ts, lib/utils/message-utils.ts
This PR improves the related questions section display and functionality.
Changes include:
- Enhanced rendering of related questions in the UI
- Improved handling of related question data in the message parts
- Updated message utility functions to support related questions
- Streamlined integration with the chat stream response
- Better user experience when selecting related questions
These changes complete the improvements to the related section display and functionality.
=> Improve related questions section display and functionality

app/api/upload/route.ts, components/attachment-preview.tsx, components/chat-panel.tsx, components/chat.tsx, components/drag-overlay.tsx, components/file-upload-button.tsx, components/render-message.tsx, components/uploaded-fileList.tsx, components/user-message.tsx, hooks/use-file-dropzone.ts, lib/db/chat.ts, lib/types/index.ts
This pull request introduces file upload functionality to the chat system
=> Feat file upload

components/attachment-preview.tsx, components/render-message.tsx, components/user-file-section.tsx, components/user-text-section.tsx
This PR refactors the user message rendering system to implement a parts-based structure, bringing consistency with assistant message rendering and improving code maintainability.
- **Split** `UserMessage` component into specialized components:
- `UserTextSection`: Handles text parts with editing functionality
- `UserFileSection`: Handles file attachments without collapsible wrapper
- **Updated** `render-message.tsx` to use parts-based rendering for user messages
- **Removed** original `user-message.tsx` component
- **Consistent Structure**: User messages now follow the same parts-based rendering pattern as assistant messages
- **Separation of Concerns**: Text and file handling are now in dedicated components
- **Maintainability**: Each part type has its own specialized component
- …
=> Refactor user message rendering to support parts-based structure

README.md
This PR updates the README.md file to improve documentation structure and acknowledge project sponsors.
- **Sponsors section** with Vercel OSS Program badge
- Moved Vercel OSS badge from header to dedicated Sponsors section
- Added "This project is proudly supported by:" description
- **License section** 
- Added clear Apache License 2.0 information
- Included link to LICENSE file
- Updated Overview section with links to new sections
- **Verified models section**
- Removed detailed model list to reduce redundancy
- Model information is already covered in AI Providers section
- **Sponsors recognition**: Properly highlight Vercel's OSS Program support in a dedicated section
- **License clarity**: Make license information easily accessible to users and contributors  
- **Documentation …
=> Update README: Add Sponsors and License sections, remove Verified models

lib/actions/chat-db.ts, lib/config/models.ts
This PR implements comprehensive caching optimization for improved page load performance in Next.js 15.
- **Replaced experimental `use cache` with stable `unstable_cache`** for production reliability
- **Implemented chat-specific cache tags** (`chat-${chatId}`) for efficient invalidation
- **Added 5-minute cache for chat data** with automatic revalidation on updates
- **Added 1-hour cache for model configuration** to reduce API calls
- **Resolved `headers()` usage inside `unstable_cache`** by moving dynamic data extraction outside cached functions
- **Fixed baseURL handling** in model loading to prevent cache scope violations
- **Optimized revalidation approach** using only `revalidateTag` (removed redundant `revalidatePath`)
- **Targeted cache invalidation** - only affected chat caches …
=> feat: Implement optimized cache with unstable_cache and chat-specific revalidation

components/chat-messages.tsx
This PR implements automatic collapsing of tool sections when multiple tools are present in a single message, improving the readability of complex AI responses.
- Modified `getIsOpen` function in `chat-messages.tsx` to detect when a message contains multiple tools
- When a message has more than one tool (search, fetch, askQuestion, relatedQuestions), they default to collapsed state
- Single tools maintain the current behavior (open by default)
- User preferences are preserved - manual open/close actions still take precedence
**Before**: All tools in a message are expanded by default, which can be overwhelming when multiple tools are used
**After**: 
- Single tool: Expanded by default (no change)
- Multiple tools: Collapsed by default for cleaner UI
- User can still manually …
=> feat: Auto-collapse multiple tools in messages

components/user-text-section.tsx
This PR fixes an issue where the edit icon was overlapping with user message text in the UserTextSection component due to improper positioning within the same container.
- **Changed parent container layout**: Replaced flex layout with relative positioning for better control over child element placement
- **Added content padding**: Added `pr-10` (padding-right: 2.5rem) to the content div to prevent text from flowing underneath the edit button
- **Adjusted button positioning**: Updated button position from `top-1 right-1` to `top-0 right-0` for precise alignment
- **Removed unnecessary classes**: Cleaned up flex layout classes that are no longer needed
The edit icon was previously overlapping with user message text because both the content and the button were competing for the same space. …
=> Fix edit icon overlapping with user messages

components/collapsible-message.tsx, components/search-section.tsx, components/tool-todo-display.tsx
This PR updates the styling of the collapsible message component to maintain consistency with the tool-todo-display component across the application.
- Updated container styling to use `rounded-lg border bg-card` to match tool-todo-display
- Added `cursor-pointer` style for better user experience on interactive elements
- Changed padding to `px-3 py-2` to align with tool-todo-display component
- Simplified content wrapper structure by removing unnecessary div
- Updated separator margins from `my-4` to `my-2` for better spacing
- Added proper content padding with `px-3 pb-2` in CollapsibleContent
- Removed hover effects (`hover:bg-accent/50 transition-colors`) as requested
- Maintained `cursor-pointer` for interactive state
- Added explicit `cursor-pointer` style for consistency
- Refined …
=> feat: align collapsible component styling for consistency

bun.lock, lib/utils/registry.ts, package.json, public/config/models.json
Added support for Vercel Gateway: https://vercel.com/docs/ai-gateway
=> Feature: support for Vercel gateway

components/changelog-banner.tsx, public/changelog.json
- Updated changelog content to better convey that Morphic has been reborn with powerful agentic search capabilities
- Added IconLogo to the changelog banner for better visual branding
- Changed feature text from generic "Adaptive search mode" to "Morphic reborn - Now with powerful agentic search beyond quick answers"
- Modified `public/changelog.json` to emphasize the evolution from quick search to agentic capabilities
- Updated `components/changelog-banner.tsx` to display the IconLogo before the version number
This better communicates the significant upgrade in v0.5.0 where Morphic evolved from just quick search to now supporting intelligent, agentic search capabilities.
=> feat: emphasize Morphic reborn with agentic search in changelog

config/models/cloud.json, config/models/default.json, lib/agents/generate-related-questions.ts, lib/config/load-models-config.ts, lib/config/model-types.ts
This PR migrates the hardcoded model configurations to external JSON files, making the system more flexible and fork-friendly.
- **Move model configurations to JSON files**: Replaced hardcoded model configurations in `model-types.ts` with external JSON configuration files
- **Add profile support**: Implemented support for profile-based configuration via `MORPHIC_MODELS_PROFILE` environment variable
- **Create configuration profiles**: Added `default.json` and `cloud.json` configuration profiles in `config/models/`
- **Implement dynamic loading**: Added `load-models-config.ts` with caching mechanism for efficient configuration loading
- **Update model accessors**: Modified `model-types.ts` to read from JSON configuration instead of hardcoded values
- **Fork-friendly**: Easier for forks to …
=> feat: migrate model configuration to JSON files

README.md, docs/CONFIGURATION.md
- Updated README.md with centered header layout and improved badge arrangement
- Added GitHub forks badge for better community visibility
- Cleaned up CONFIGURATION.md by removing deprecated Redis/chat history sections
- Updated model configuration documentation to match new JSON structure
- Added Vercel AI Gateway as a supported provider
- Removed outdated features and simplified content throughout
- Centered header section with logo and description
- Added GitHub forks badge alongside stars badge
- Arranged badges horizontally for better visual presentation
- Maintained Vercel OSS badge and TrendShift badge placement
- Removed deprecated Chat History Storage section (Redis no longer used)
- Updated model configuration format to match new `config/models/*.json` structure
- Added …
=> feat: update documentation for v1.0 release

.github/workflows/ci.yml, components/chat-panel.tsx, config/models/cloud.json, lib/agents/prompts/search-mode-prompts.ts, lib/agents/researcher.ts, lib/streaming/create-chat-stream-response.ts, lib/utils/model-selection.ts
- Update model configuration to use GPT-5 for quality mode with reasoning support
- Increase max steps for planning and adaptive modes from 20-30 to 50 for better search depth
- Remove tool invocation checks for button states to improve UI responsiveness
- Optimize import ordering in chat-panel for better code organization
- **Model Configuration**: Updated quality mode to use GPT-5 with reasoning effort and summary settings
- **Search Enhancement**: Increased max steps to 50 for both planning and adaptive modes to allow more thorough research
- **UI Improvements**: Simplified button state logic by removing unnecessary tool invocation checks
- **Code Quality**: Reorganized imports in chat-panel.tsx for better maintainability
=> feat: update prompt format and search configuration

lib/agents/prompts/search-mode-prompts.ts, scripts/README.md, scripts/chat-cli.ts
This PR introduces comprehensive improvements to the AI prompt system, focusing on eliminating text-based planning issues and enhancing search mode capabilities. The changes improve AI response quality by enforcing proper tool usage and optimizing search behavior.
- Updated chat CLI to support new API with model types and search modes
- Added support for cookie-based API authentication for model selection
- Enhanced CLI parameter handling for better user experience
- Eliminated problematic text-based planning output in favor of structured todoWrite tool usage
- Fixed AI outputting plans as plain text instead of using proper tool calls
- Improved prompt clarity to enforce correct tool usage patterns
- Improved URL detection logic to skip unnecessary search operations when URLs are provided …
=> feat: enhance AI prompt system with improved planning and search capabilities
